### ISSUE TITLE
Request body doesn't fulfill schema, see details in `fields` (New Image)

### ISSUE THREAD

**Issue by k2gremlin** [peteward44/docker-godaddy-ddns#2]
I know an existing issue has been closed with this same topic. I tried with a new :latest image and I still get the error. 
<domain> is my domain and X.X.X.X is the correct IP. 
bash-4.3# ./godaddy-ddns.sh                                                                                
Checking current 'Public IP' from 'http://api.ipify.org'...X.X.X.X!                                 
Checking '<domain>.com' IP records from 'GoDaddy'...changed!                                              
Updating '<domain>'...Fail! {"code":"INVALID_BODY","fields":[{"code":"UNEXPECTED_TYPE","message":"is n
ot a array","path":"records"}],"message":"Request body doesn't fulfill schema, see details in `fields`"}

**Comment by peteward44** [comment]
Looks like GoDaddy's API has changed again, i've updated the code & docker hub image i just need to test it now

**Comment by k2gremlin** [comment]
Thanks a ton! Appreciate it.

**Comment by peteward44** [comment]
seems to work for me. Pull the new docker image and give it a go 👍

**Comment by k2gremlin** [comment]
![screenshot_2](https://user-images.githubusercontent.com/10319833/40883300-2d3ce1b0-66c7-11e8-99a9-275810d913f8.png)


Still not working. Attached a screenshot showing the fresh build. 

Am I doing something wrong?

**Comment by peteward44** [comment]
OK looking at the error message it complains it can't find the domain name, so i would make sure there are no typos in your domain name, and that it already has a zone file created in godaddy's admin area (this script just changes existing ones, it doesn't create them)

Also make sure that domain and subdomain are specified correctly, so for www.domain.com will be
```
        -e "GODADDY_DOMAIN=domain.com" \
        -e "GODADDY_TYPE=A" \
        -e "GODADDY_NAME=www" \
```

**Comment by k2gremlin** [comment]
added the type A and Name www and it still fails. Godaddy dns management shows a Type A record Name: @ and value is my IP. I manually set this when this issue first started happening.

**Comment by k2gremlin** [comment]
Helps if I don't have an extra . on my domain. All good. Issue fixed :)

**Comment by peteward44** [comment]
:+1:
